### ISSUE TITLE
Error while loading file with pynwb

### ISSUE THREAD

**Issue by filippomc** [LorenFrankLab/franklab-nwb-hack#1]
Hello, thanks for the notebook, I'm really appreciating the clear description with the mapping of the experiment concepts with pynwb objects.

I'm having a problem loading the file at https://www.dropbox.com/s/92jkkse2c7lm7qe/bon04.nwb?dl=0:
`Exception: ('File error', ValueError('Error reading the NWB file.', ("'franklab' not a namespace",)))`

I'm using the last dev version. Maybe a patched version of pynwb was used to generate the file?
Thanks in advance.

**Comment by filippomc** [comment]
I figured out I needed to install the extension. Sorry for bothering!

**Comment by tjd2002** [comment]
Glad it’s proving useful!
